export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"

export const GET_ERROR = "GET_ALL_CATEGORY"

// subcategory
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"

//Brand
export const GET_ALL_BRAND  = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_ONE_BRAND = "GET_ONE_BRAND"

// product
export const CREATE_PRODUCTS = "CREATE_PRODUCTS"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

// Auth
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const VERIFY_CODE = "VERIFY_CODE"
export const RESET_PASSWORD = "RESET_PASSWORD"

// create review
export const CREATE_REVIEW = "CREATE_REVIEW"
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT"
export const DELETE_REVIEW_PRODUCT = "DELETE_REVIEW_PRODUCT"